# Generated by Django 5.0.7 on 2024-07-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_amount_actual_event_amount_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='amount_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
