# Generated by Django 5.0.7 on 2024-07-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_validated',
            field=models.BooleanField(default=True),
        ),
    ]
